# @name get-prompts
GET http://localhost:3333/prompts

###

# @name upload
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----VideoTeste

------VideoTeste
Content-Disposition: form-data; name="file"; filename="video-alvaro.mp3"
Content-Type: audio/mpeg

< ./video-alvaro.mp3

------VideoTeste--

###

# @name create-transcription
POST http://localhost:3333/videos/99f9c32f-d70d-4dd5-998b-9d2839434d80/transcription
Content-Type: application/json

{
    "prompt": "startup, inovação, tecnologia"
}

###

# @name generate-ai-completion
POST http://localhost:3333/ai/complete
Content-Type: application/json

{
    "videoId": "6a50d51a-292d-4865-ba12-81cb8d8233cd",
    "temperature": 0.5,
    "prompt": "Gere um resumo sucinto da transcrição do vídeo informado a seguir: ''' {transcription} '''"
}